<?php
/**
 * Campaign List Controller Class
 *
 * @package    SmartCycleDiscounts
 * @subpackage SmartCycleDiscounts/includes/core/campaigns/class-campaign-list-controller.php
 * @author     Webstepper <contact@webstepper.io>
 * @copyright  2025 Webstepper
 * @license    GPL-3.0-or-later https://www.gnu.org/licenses/gpl-3.0.html
 * @link       https://webstepper.io/wordpress-plugins/smart-cycle-discounts
 * @since      1.0.0
 */


if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}


/**
 * Campaign List Controller Class
 *
 * @since      1.0.0
 */
class WSSCD_Campaign_List_Controller extends WSSCD_Abstract_Campaign_Controller {

	/**
	 * List table instance.
	 *
	 * @since    1.0.0
	 * @var      WSSCD_Campaigns_List_Table|null
	 */
	private ?WSSCD_Campaigns_List_Table $list_table = null;

	/**
	 * Wizard state service.
	 *
	 * @since    1.0.0
	 * @var      WSSCD_Wizard_State_Service
	 */
	private WSSCD_Wizard_State_Service $wizard_state_service;

	/**
	 * Feature gate instance.
	 *
	 * @since    1.0.0
	 * @var      WSSCD_Feature_Gate
	 */
	private WSSCD_Feature_Gate $feature_gate;

	/**
	 * Initialize the controller.
	 *
	 * @since    1.0.0
	 * @param    WSSCD_Campaign_Manager         $campaign_manager      Campaign manager.
	 * @param    WSSCD_Admin_Capability_Manager $capability_manager    Capability manager.
	 * @param    WSSCD_Logger                   $logger                Logger instance.
	 * @param    WSSCD_Wizard_State_Service     $wizard_state_service  Wizard state service.
	 * @param    WSSCD_Feature_Gate             $feature_gate          Feature gate.
	 */
	public function __construct(
		WSSCD_Campaign_Manager $campaign_manager,
		WSSCD_Admin_Capability_Manager $capability_manager,
		WSSCD_Logger $logger,
		WSSCD_Wizard_State_Service $wizard_state_service,
		WSSCD_Feature_Gate $feature_gate
	) {
		parent::__construct( $campaign_manager, $capability_manager, $logger );
		$this->wizard_state_service = $wizard_state_service;
		$this->feature_gate         = $feature_gate;
	}

	/**
	 * Handle the list display.
	 *
	 * @since    1.0.0
	 * @return   void
	 */
	public function handle(): void {
		if ( ! $this->check_capability( 'wsscd_view_campaigns' ) ) {
			wp_die( esc_html__( 'You do not have permission to view campaigns.', 'smart-cycle-discounts' ) );
		}

		// Handle discard draft action
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Nonce is verified in handle_discard_draft().
		if ( isset( $_GET['action'] ) && 'discard_draft' === sanitize_key( $_GET['action'] ) ) {
			$this->handle_discard_draft();
			return;
		}

		$this->init_list_table();

		// Handle bulk actions
		$this->handle_bulk_actions();

		// Enqueue required scripts
		$this->enqueue_scripts();

		$this->render();
	}

	/**
	 * Initialize list table.
	 *
	 * @since    1.0.0
	 * @return   void
	 */
	private function init_list_table(): void {
		if ( ! class_exists( 'WSSCD_Campaigns_List_Table' ) ) {
			require_once WSSCD_INCLUDES_DIR . 'admin/components/class-campaigns-list-table.php';
		}

		$this->list_table = new WSSCD_Campaigns_List_Table( $this->campaign_manager, $this->capability_manager );
		$this->list_table->prepare_items();
	}

	/**
	 * Handle bulk actions.
	 *
	 * @since    1.0.0
	 * @return   void
	 */
	private function handle_bulk_actions(): void {
		if ( ! $this->list_table ) {
			return;
		}

		$action = $this->list_table->current_action();
		if ( ! $action ) {
			return;
		}

		// SECURITY: Nonce verification using WordPress standard 'bulk-campaigns' action.
		// This nonce is generated by WP_List_Table and verified here before any bulk operations are processed.
		if ( ! wp_verify_nonce( isset( $_REQUEST['_wpnonce'] ) ? sanitize_text_field( wp_unslash( $_REQUEST['_wpnonce'] ) ) : '', 'bulk-campaigns' ) ) {
			return;
		}

		// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Values are sanitized with absint().
		$campaign_ids = array_map( 'absint', isset( $_REQUEST['campaign'] ) ? $_REQUEST['campaign'] : array() );
		if ( empty( $campaign_ids ) ) {
			return;
		}

		switch ( $action ) {
			case 'delete':
				$this->handle_bulk_delete( $campaign_ids );
				break;
			case 'activate':
				$this->handle_bulk_activate( $campaign_ids );
				break;
			case 'deactivate':
				$this->handle_bulk_deactivate( $campaign_ids );
				break;
		}
	}

	/**
	 * Handle bulk delete.
	 *
	 * @since    1.0.0
	 * @param    array $campaign_ids    Campaign IDs.
	 * @return   void
	 */
	private function handle_bulk_delete( array $campaign_ids ): void {
		if ( ! $this->check_capability( 'wsscd_delete_campaigns' ) ) {
			return;
		}

		$deleted = 0;
		foreach ( $campaign_ids as $id ) {
			if ( $this->campaign_manager->delete_campaign( $id ) ) {
				++$deleted;
			}
		}

		$this->add_notice(
			sprintf(
				/* translators: %d: number of campaigns deleted */
				_n(
					'%d campaign deleted.',
					'%d campaigns deleted.',
					$deleted,
					'smart-cycle-discounts'
				),
				$deleted
			),
			'success'
		);
	}

	/**
	 * Handle bulk activate.
	 *
	 * @since    1.0.0
	 * @param    array $campaign_ids    Campaign IDs.
	 * @return   void
	 */
	private function handle_bulk_activate( array $campaign_ids ): void {
		if ( ! $this->check_capability( 'wsscd_edit_campaigns' ) ) {
			return;
		}

		$activated = 0;
		foreach ( $campaign_ids as $id ) {
			if ( $this->campaign_manager->activate_campaign( $id ) ) {
				++$activated;
			}
		}

		$this->add_notice(
			sprintf(
				/* translators: %d: number of campaigns activated */
				_n(
					'%d campaign activated.',
					'%d campaigns activated.',
					$activated,
					'smart-cycle-discounts'
				),
				$activated
			),
			'success'
		);
	}

	/**
	 * Handle bulk deactivate.
	 *
	 * @since    1.0.0
	 * @param    array $campaign_ids    Campaign IDs.
	 * @return   void
	 */
	private function handle_bulk_deactivate( array $campaign_ids ): void {
		if ( ! $this->check_capability( 'wsscd_edit_campaigns' ) ) {
			return;
		}

		$deactivated = 0;
		foreach ( $campaign_ids as $id ) {
			if ( $this->campaign_manager->deactivate_campaign( $id ) ) {
				++$deactivated;
			}
		}

		$this->add_notice(
			sprintf(
				/* translators: %d: number of campaigns deactivated */
				_n(
					'%d campaign deactivated.',
					'%d campaigns deactivated.',
					$deactivated,
					'smart-cycle-discounts'
				),
				$deactivated
			),
			'success'
		);
	}

	/**
	 * Handle discard draft action.
	 *
	 * @since    1.0.0
	 * @return   void
	 */
	private function handle_discard_draft(): void {
		// Verify nonce
		if ( ! isset( $_GET['_wpnonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_GET['_wpnonce'] ) ), 'wsscd_discard_draft' ) ) {
			wp_die( esc_html__( 'Security check failed.', 'smart-cycle-discounts' ) );
		}

		if ( ! $this->check_capability( 'wsscd_create_campaigns' ) ) {
			wp_die( esc_html__( 'You do not have permission to discard drafts.', 'smart-cycle-discounts' ) );
		}

		// Discard the draft
		$this->wizard_state_service->clear_session();

		if ( isset( $_GET['redirect'] ) ) {
			$redirect_url = urldecode( sanitize_text_field( wp_unslash( $_GET['redirect'] ) ) );
			if ( strpos( $redirect_url, admin_url() ) === 0 ) {
				wp_safe_redirect( $redirect_url );
				exit;
			}
		}

		// Default redirect with success message
		wp_safe_redirect(
			add_query_arg(
				array(
					'page'    => 'wsscd-campaigns',
					'message' => 'draft_discarded',
				),
				admin_url( 'admin.php' )
			)
		);
		exit;
	}

	/**
	 * Enqueue required scripts for the campaigns page.
	 *
	 * @since    1.0.0
	 * @return   void
	 */
	private function enqueue_scripts(): void {
		// Ensure UI utilities are loaded for modal functionality
		wp_enqueue_script( 'wsscd-shared-ui' );
	}

	/**
	 * Render the list page.
	 *
	 * @since    1.0.0
	 * @return   void
	 */
	private function render(): void {
		?>
		<div class="wrap">
			<h1 class="wp-heading-inline">
				<?php echo esc_html__( 'Campaigns', 'smart-cycle-discounts' ); ?>
			</h1>
			
			<?php
			// Display success messages
			// phpcs:disable WordPress.Security.NonceVerification.Recommended -- Read-only URL parameter for displaying messages after redirect.
			if ( isset( $_GET['message'] ) ) {
				$message  = sanitize_text_field( wp_unslash( $_GET['message'] ) );
				// phpcs:enable WordPress.Security.NonceVerification.Recommended
				$messages = array(
					'draft_discarded' => __( 'Draft campaign has been discarded.', 'smart-cycle-discounts' ),
					'activated'       => __( 'Campaign activated successfully.', 'smart-cycle-discounts' ),
					'deactivated'     => __( 'Campaign deactivated successfully.', 'smart-cycle-discounts' ),
					'deleted'         => __( 'Campaign moved to trash successfully.', 'smart-cycle-discounts' ),
				);
				if ( isset( $messages[ $message ] ) ) {
					?>
					<div class="notice notice-success is-dismissible">
						<p><?php echo esc_html( $messages[ $message ] ); ?></p>
					</div>
					<?php
				}
			}

			// Display error messages
			// phpcs:disable WordPress.Security.NonceVerification.Recommended -- Read-only URL parameter for displaying errors after redirect.
			if ( isset( $_GET['error'] ) ) {
				$error  = sanitize_text_field( wp_unslash( $_GET['error'] ) );
				// phpcs:enable WordPress.Security.NonceVerification.Recommended
				$errors = array(
					'activate_failed'   => __( 'Failed to activate campaign.', 'smart-cycle-discounts' ),
					'deactivate_failed' => __( 'Failed to deactivate campaign.', 'smart-cycle-discounts' ),
					'delete_failed'     => __( 'Failed to delete campaign.', 'smart-cycle-discounts' ),
				);
				if ( isset( $errors[ $error ] ) ) {
					?>
					<div class="notice notice-error is-dismissible">
						<p><?php echo esc_html( $errors[ $error ] ); ?></p>
					</div>
					<?php
				}
			}

			?>

			<?php
			// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Read-only URL parameter for filtering campaigns.
			$viewing_trash = isset( $_REQUEST['status'] ) && 'trash' === sanitize_key( $_REQUEST['status'] );

			$draft_info = null;
			?>

			<?php if ( ! $viewing_trash && $this->check_capability( 'wsscd_create_campaigns' ) ) : ?>
				<?php
				$draft_info = $this->wizard_state_service->get_draft_info();
				$has_draft  = $draft_info && empty( $draft_info['is_expired'] );

				if ( $has_draft ) {
					$session_type  = 'draft';
					$campaign_name = $draft_info['campaign_name'] ?? '';
					$last_activity = ! empty( $draft_info['last_updated'] ) ?
						human_time_diff( $draft_info['last_updated'], current_time( 'timestamp' ) ) : '';
				} else {
					$session_type  = 'none';
					$campaign_name = '';
					$last_activity = '';
				}
				?>
				<a href="<?php echo esc_url( admin_url( 'admin.php?page=wsscd-campaigns&action=wizard&intent=new' ) ); ?>"
					class="page-title-action wsscd-new-campaign-btn"
					data-has-session="<?php echo esc_attr( $has_draft ? 'true' : 'false' ); ?>"
					data-session-type="<?php echo esc_attr( $session_type ); ?>"
					data-campaign-name="<?php echo esc_attr( $campaign_name ); ?>"
					data-last-activity="<?php echo esc_attr( $last_activity ); ?>">
					<?php echo esc_html__( 'Add New Campaign', 'smart-cycle-discounts' ); ?>
				</a>

				<?php if ( $has_draft ) : ?>
					<a href="<?php echo esc_url( admin_url( 'admin.php?page=wsscd-campaigns&action=wizard&intent=continue' ) ); ?>"
						class="page-title-action">
						<?php
						WSSCD_Icon_Helper::render( 'edit', array( 'size' => 16 ) );
						?>
						<?php echo esc_html__( 'Continue Draft', 'smart-cycle-discounts' ); ?>
					</a>
				<?php endif; ?>
			<?php endif; ?>

			<hr class="wp-header-end">

			<?php
			// Display draft notice if exists
			if ( $draft_info && $this->check_capability( 'wsscd_create_campaigns' ) ) {
				$this->render_draft_notice( $draft_info );
			}
			?>

			<?php $this->list_table->views(); ?>

			<form method="post">
				<?php
				$this->list_table->search_box( __( 'Search Campaigns', 'smart-cycle-discounts' ), 'campaign' );
				$this->list_table->display();
				?>
			</form>

			<?php
			if ( method_exists( $this->list_table, 'inline_edit' ) ) {
				$this->list_table->inline_edit();
			}
			?>
		</div>

		<?php
		// Render campaign overview panel
		$this->render_overview_panel();

		if ( $this->check_capability( 'wsscd_create_campaigns' ) ) {
			$this->render_draft_conflict_modal();
			$this->enqueue_modal_scripts();
		}
	}

	/**
	 * Render draft campaign notice.
	 *
	 * Enhanced with accessibility features, icons, and improved layout.
	 *
	 * @since    1.0.0
	 * @param    array $draft_info    Draft campaign information.
	 * @return   void
	 */
	private function render_draft_notice( array $draft_info ): void {
		// Calculate time remaining until expiration (2 hours = 7200 seconds)
		$last_updated      = $draft_info['last_updated'] ?? time();
		$session_lifetime  = 7200; // Should match WSSCD_Wizard_State_Service::SESSION_LIFETIME
		$time_elapsed      = time() - $last_updated;
		$time_remaining    = $session_lifetime - $time_elapsed;
		$minutes_remaining = max( 0, floor( $time_remaining / 60 ) );
		$hours_remaining   = floor( $minutes_remaining / 60 );
		$mins_only         = $minutes_remaining % 60;

		// Determine urgency level
		if ( $minutes_remaining <= 15 ) {
			$urgency_class = 'wsscd-expiration-urgent';
		} elseif ( $minutes_remaining <= 30 ) {
			$urgency_class = 'wsscd-expiration-warning';
		} else {
			$urgency_class = 'wsscd-expiration-normal';
		}
		?>
		<div class="notice notice-info wsscd-draft-notice" role="status" aria-live="polite" aria-atomic="true">
			<p>
				<?php
				WSSCD_Icon_Helper::render( 'info', array( 'size' => 20 ) );
				?>
				<span class="wsscd-draft-label">
					<?php echo esc_html__( 'Draft:', 'smart-cycle-discounts' ); ?>
				</span>
				<strong class="wsscd-draft-campaign-name"><?php echo esc_html( $draft_info['campaign_name'] ); ?></strong>

				<?php if ( ! empty( $draft_info['last_updated'] ) ) : ?>
					<span class="wsscd-draft-meta" aria-label="<?php echo esc_attr__( 'Last activity timestamp', 'smart-cycle-discounts' ); ?>">
						<?php
						printf(
							/* translators: %s: Human readable time difference */
							esc_html__( '(edited %s ago)', 'smart-cycle-discounts' ),
							esc_html( human_time_diff( $draft_info['last_updated'], time() ) )
						);
						?>
					</span>
				<?php endif; ?>

				<span class="wsscd-draft-expiration <?php echo esc_attr( $urgency_class ); ?>" aria-label="<?php echo esc_attr__( 'Draft expiration time', 'smart-cycle-discounts' ); ?>">
					<?php
					if ( $hours_remaining > 0 ) {
						printf(
							/* translators: 1: hours, 2: minutes */
							esc_html__( 'Expires in %1$d hour %2$d min', 'smart-cycle-discounts' ),
							absint( $hours_remaining ),
							absint( $mins_only )
						);
					} elseif ( $minutes_remaining > 1 ) {
						printf(
							/* translators: %d: minutes */
							esc_html__( 'Expires in %d minutes', 'smart-cycle-discounts' ),
							absint( $minutes_remaining )
						);
					} elseif ( $minutes_remaining === 1 ) {
						echo esc_html__( 'Expires in 1 minute', 'smart-cycle-discounts' );
					} else {
						echo esc_html__( 'Expiring soon', 'smart-cycle-discounts' );
					}
					?>
				</span>

				<span class="wsscd-draft-actions" role="group" aria-label="<?php echo esc_attr__( 'Draft campaign actions', 'smart-cycle-discounts' ); ?>">
					<a href="<?php echo esc_url( admin_url( 'admin.php?page=wsscd-campaigns&action=wizard&intent=continue' ) ); ?>"
						class="wsscd-button wsscd-button-primary"
						aria-label="<?php echo esc_attr__( 'Resume editing draft campaign', 'smart-cycle-discounts' ); ?>">
						<?php echo esc_html__( 'Resume', 'smart-cycle-discounts' ); ?>
					</a>

					<a href="
					<?php
					echo esc_url(
						wp_nonce_url(
							admin_url( 'admin.php?page=wsscd-campaigns&action=discard_draft' ),
							'wsscd_discard_draft',
							'_wpnonce'
						)
					);
					?>
					"
						class="wsscd-button wsscd-button-secondary wsscd-button-danger"
						role="button"
						aria-label="<?php echo esc_attr__( 'Discard draft campaign', 'smart-cycle-discounts' ); ?>"
						onclick="return confirm('<?php echo esc_attr__( 'Are you sure you want to discard this draft campaign?', 'smart-cycle-discounts' ); ?>');">
						<?php echo esc_html__( 'Discard Draft', 'smart-cycle-discounts' ); ?>
					</a>
				</span>
			</p>
		</div>
		<?php
	}

	/**
	 * Render draft conflict modal.
	 *
	 * Handles unsaved draft campaigns.
	 *
	 * @since    1.0.0
	 * @return   void
	 */
	private function render_draft_conflict_modal(): void {
		require_once WSSCD_INCLUDES_DIR . 'admin/components/class-modal-component.php';

		// Get draft info for enhanced modal content
		$draft_info = $this->wizard_state_service->get_draft_info();

		// Build enhanced modal content with draft details
		$content = '<div id="wsscd-modal-message">';

		if ( $draft_info ) {
			// Campaign name
			$content .= '<p>';
			$content .= esc_html__( 'You have an unfinished campaign in progress:', 'smart-cycle-discounts' );
			$content .= '</p>';
			$content .= '<p>';
			$content .= '<strong>' . esc_html( $draft_info['campaign_name'] ) . '</strong>';
			$content .= '</p>';

			// Draft meta information (timestamp and expiration)
			$content .= '<div class="wsscd-modal__draft-meta">';

			// Last updated timestamp - use wp_kses with SVG allowed tags since wp_kses_post strips SVG.
			if ( ! empty( $draft_info['last_updated'] ) ) {
				$content .= '<div class="wsscd-modal__draft-meta-item">';
				$content .= wp_kses( WSSCD_Icon_Helper::get( 'clock', array( 'size' => 16 ) ), WSSCD_Icon_Helper::get_allowed_svg_tags() );
				$content .= '<span>';
				$content .= sprintf(
					/* translators: %s: Human readable time difference */
					esc_html__( 'Last edited %s ago', 'smart-cycle-discounts' ),
					esc_html( human_time_diff( $draft_info['last_updated'], time() ) )
				);
				$content .= '</span>';
				$content .= '</div>';
			}

			// Expiration timer
			$last_updated      = $draft_info['last_updated'] ?? time();
			$session_lifetime  = 7200; // 2 hours
			$time_elapsed      = time() - $last_updated;
			$time_remaining    = $session_lifetime - $time_elapsed;
			$minutes_remaining = max( 0, floor( $time_remaining / 60 ) );
			$hours_remaining   = floor( $minutes_remaining / 60 );
			$mins_only         = $minutes_remaining % 60;

			// Determine urgency level
			if ( $minutes_remaining <= 15 ) {
				$urgency_class = 'wsscd-expiration-urgent';
			} elseif ( $minutes_remaining <= 30 ) {
				$urgency_class = 'wsscd-expiration-warning';
			} else {
				$urgency_class = 'wsscd-expiration-normal';
			}

			$content .= '<div class="wsscd-modal__draft-meta-item">';
			$content .= '<span class="wsscd-modal__expiration ' . esc_attr( $urgency_class ) . '">';
			if ( $hours_remaining > 0 ) {
				$content .= sprintf(
					/* translators: 1: hours, 2: minutes */
					esc_html__( 'Draft expires in %1$d hour %2$d min', 'smart-cycle-discounts' ),
					$hours_remaining,
					$mins_only
				);
			} elseif ( $minutes_remaining > 1 ) {
				$content .= sprintf(
					/* translators: %d: minutes */
					esc_html__( 'Draft expires in %d minutes', 'smart-cycle-discounts' ),
					$minutes_remaining
				);
			} elseif ( $minutes_remaining === 1 ) {
				$content .= esc_html__( 'Draft expires in 1 minute', 'smart-cycle-discounts' );
			} else {
				$content .= esc_html__( 'Draft expiring soon', 'smart-cycle-discounts' );
			}
			$content .= '</span>';
			$content .= '</div>';

			$content .= '</div>'; // .wsscd-modal__draft-meta

			// Action prompt
			$content .= '<p>';
			$content .= esc_html__( 'Would you like to continue working on this draft or start fresh?', 'smart-cycle-discounts' );
			$content .= '</p>';
		}

		$content .= '</div>';

		$modal_config = array(
			'id'             => 'wsscd-draft-conflict-modal',
			'title'          => esc_html__( 'Unfinished Campaign Found', 'smart-cycle-discounts' ),
			'content'        => $content,
			'icon'           => 'info',
			'classes'        => array( 'wsscd-modal__icon--info' ),
			'buttons'        => array(
				array(
					'id'     => 'wsscd-continue-draft',
					'text'   => __( 'Resume Campaign', 'smart-cycle-discounts' ),
					'class'  => 'wsscd-button wsscd-button-primary',
					'action' => 'continue',
					'icon'   => 'edit',
				),
				array(
					'id'     => 'wsscd-discard-and-new',
					'text'   => __( 'Start New Campaign', 'smart-cycle-discounts' ),
					'class'  => 'wsscd-button wsscd-button-danger wsscd-discard-btn',
					'action' => 'discard-new',
					'icon'   => 'trash',
				),
				array(
					'text'   => __( 'Go Back', 'smart-cycle-discounts' ),
					'class'  => 'wsscd-button wsscd-button-secondary wsscd-modal-cancel',
					'action' => 'close',
					'icon'   => 'no',
				),
			),
			'escape_content' => false, // Already escaped above
		);

		$modal = new WSSCD_Modal_Component( $modal_config );
		$modal->render();
	}

	/**
	 * Enqueue modal scripts and localization.
	 *
	 * @since    1.0.0
	 * @return   void
	 */
	private function enqueue_modal_scripts(): void {
		// Enqueue campaign list modals script
		wp_enqueue_script( 'wsscd-campaign-list-modals' );

		// Localize script with translations and URLs
		wp_localize_script(
			'wsscd-campaign-list-modals',
			'wsscdCampaignListL10n',
			array(
				'discardingText' => esc_html__( 'Discarding...', 'smart-cycle-discounts' ),
				'adminUrl'       => admin_url( 'admin.php' ),
				'nonce'          => wp_create_nonce( 'wsscd_wizard_nonce' ),
			)
		);
	}

	/**
	 * Render campaign overview panel.
	 *
	 * @since    1.0.0
	 * @return   void
	 */
	private function render_overview_panel(): void {
		echo '<!-- WSSCD: render_overview_panel() called -->';

		// Get panel component from container
		try {
			$plugin = Smart_Cycle_Discounts::get_instance();
			echo '<!-- WSSCD: Plugin instance retrieved -->';

			if ( ! $plugin ) {
				echo '<!-- WSSCD: Plugin instance is null -->';
				return;
			}

			if ( ! method_exists( $plugin, 'get_container' ) ) {
				echo '<!-- WSSCD: get_container method does not exist -->';
				return;
			}

			$container = $plugin->get_container();
			echo '<!-- WSSCD: Container retrieved -->';

			if ( ! $container ) {
				echo '<!-- WSSCD: Container is null -->';
				return;
			}

			if ( ! $container->has( 'campaign_overview_panel' ) ) {
				echo '<!-- WSSCD: campaign_overview_panel service not found in container -->';
				return;
			}

			echo '<!-- WSSCD: campaign_overview_panel service exists -->';

			$panel = $container->get( 'campaign_overview_panel' );
			echo '<!-- WSSCD: Panel instance retrieved -->';

			if ( ! $panel ) {
				echo '<!-- WSSCD: Panel instance is null -->';
				return;
			}

			if ( ! method_exists( $panel, 'render' ) ) {
				echo '<!-- WSSCD: render method does not exist on panel -->';
				return;
			}

			echo '<!-- WSSCD: About to call panel->render() -->';
			$panel->render();
			echo '<!-- WSSCD: panel->render() completed -->';

		} catch ( Exception $e ) {
			echo '<!-- WSSCD: Exception caught: ' . esc_html( $e->getMessage() ) . ' -->';
			if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
				// phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log -- Intentional debug logging when WP_DEBUG is enabled.
				error_log( 'WSSCD Campaign Overview Panel Error: ' . $e->getMessage() );
			}
		}
	}
}