<?php
/**
 * Campaign Calculator Class
 *
 * @package    SmartCycleDiscounts
 * @subpackage SmartCycleDiscounts/includes/core/campaigns/class-campaign-calculator.php
 * @author     Webstepper <contact@webstepper.io>
 * @copyright  2025 Webstepper
 * @license    GPL-3.0-or-later https://www.gnu.org/licenses/gpl-3.0.html
 * @link       https://webstepper.io/wordpress-plugins/smart-cycle-discounts
 * @since      1.0.0
 */


if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}


/**
 * Campaign Calculator Class
 *
 * @since      1.0.0
 * @package    SmartCycleDiscounts
 * @subpackage SmartCycleDiscounts/includes/database/models
 */
class SCD_Campaign_Calculator {

	/**
	 * Analytics repository.
	 *
	 * @since    1.0.0
	 * @var      object|null
	 */
	private $analytics_repository;

	/**
	 * Product selector.
	 *
	 * @since    1.0.0
	 * @var      object|null
	 */
	private $product_selector;

	/**
	 * Constructor.
	 *
	 * @since    1.0.0
	 * @param    object|null $analytics_repository    Analytics repository.
	 * @param    object|null $product_selector        Product selector.
	 */
	public function __construct( $analytics_repository = null, $product_selector = null ) {
		$this->analytics_repository = $analytics_repository;
		$this->product_selector     = $product_selector;
	}

	/**
	 * Calculate revenue generated by campaign.
	 *
	 * @since    1.0.0
	 * @param    SCD_Campaign $campaign    Campaign object.
	 * @return   float                        Revenue amount.
	 */
	public function calculate_revenue( SCD_Campaign $campaign ): float {
		if ( ! $this->analytics_repository ) {
			return 0.0;
		}

		$campaign_id = $campaign->get_id();
		if ( ! $campaign_id ) {
			return 0.0;
		}

		$revenue = $this->analytics_repository->get_campaign_revenue( $campaign_id );

		return (float) $revenue;
	}

	/**
	 * Calculate conversion rate.
	 *
	 * @since    1.0.0
	 * @param    SCD_Campaign $campaign    Campaign object.
	 * @return   float                        Conversion rate percentage.
	 */
	public function calculate_conversion_rate( SCD_Campaign $campaign ): float {
		if ( ! $this->analytics_repository ) {
			return 0.0;
		}

		$campaign_id = $campaign->get_id();
		if ( ! $campaign_id ) {
			return 0.0;
		}

		$stats = $this->analytics_repository->get_campaign_stats( $campaign_id );

		$impressions = (int) ( $stats['impressions'] ?? 0 );
		$conversions = (int) ( $stats['conversions'] ?? 0 );

		if ( $impressions === 0 ) {
			return 0.0;
		}

		return ( $conversions / $impressions ) * 100;
	}

	/**
	 * Calculate effective discount amount.
	 *
	 * @since    1.0.0
	 * @param    SCD_Campaign $campaign       Campaign object.
	 * @param    float        $base_price     Base price.
	 * @param    int          $quantity       Quantity.
	 * @return   float                           Discount amount.
	 */
	public function calculate_discount_amount( SCD_Campaign $campaign, float $base_price, int $quantity = 1 ): float {
		$discount_type  = $campaign->get_discount_type();
		$discount_value = $campaign->get_discount_value();

		switch ( $discount_type ) {
			case 'percentage':
				return ( $base_price * $quantity ) * ( $discount_value / 100 );

			case 'fixed':
				return min( $discount_value, $base_price * $quantity );

			case 'buy_x_get_y':
				return $this->calculate_bogo_discount( $campaign, $base_price, $quantity );

			case 'tiered':
				return $this->calculate_tiered_discount( $campaign, $base_price, $quantity );

			case 'bulk':
				return $this->calculate_bulk_discount( $campaign, $base_price, $quantity );

			default:
				return 0.0;
		}
	}

	/**
	 * Calculate Buy X Get Y discount.
	 *
	 * @since    1.0.0
	 * @param    SCD_Campaign $campaign       Campaign object.
	 * @param    float        $base_price     Base price.
	 * @param    int          $quantity       Quantity.
	 * @return   float                           Discount amount.
	 */
	private function calculate_bogo_discount( SCD_Campaign $campaign, float $base_price, int $quantity ): float {
		$rules = $campaign->get_discount_rules();

		$buy_quantity     = (int) ( $rules['buy_quantity'] ?? 1 );
		$get_quantity     = (int) ( $rules['get_quantity'] ?? 1 );
		$discount_percent = (float) ( $rules['discount_percent'] ?? 100 );

		if ( $buy_quantity <= 0 || $quantity < $buy_quantity ) {
			return 0.0;
		}

		$sets      = floor( $quantity / ( $buy_quantity + $get_quantity ) );
		$remainder = $quantity % ( $buy_quantity + $get_quantity );

		$free_items = $sets * $get_quantity;
		if ( $remainder > $buy_quantity ) {
			$free_items += min( $get_quantity, $remainder - $buy_quantity );
		}

		return $free_items * $base_price * ( $discount_percent / 100 );
	}

	/**
	 * Calculate tiered discount.
	 *
	 * @since    1.0.0
	 * @param    SCD_Campaign $campaign       Campaign object.
	 * @param    float        $base_price     Base price.
	 * @param    int          $quantity       Quantity.
	 * @return   float                           Discount amount.
	 */
	private function calculate_tiered_discount( SCD_Campaign $campaign, float $base_price, int $quantity ): float {
		$rules = $campaign->get_discount_rules();
		$tiers = $rules['tiers'] ?? array();

		if ( empty( $tiers ) ) {
			return 0.0;
		}

		usort(
			$tiers,
			function ( $a, $b ) {
				return ( $b['min_quantity'] ?? 0 ) - ( $a['min_quantity'] ?? 0 );
			}
		);

		// Find applicable tier
		$applicable_tier = null;
		foreach ( $tiers as $tier ) {
			if ( $quantity >= ( $tier['min_quantity'] ?? 0 ) ) {
				$applicable_tier = $tier;
				break;
			}
		}

		if ( ! $applicable_tier ) {
			return 0.0;
		}

		$discount_type  = $applicable_tier['type'] ?? 'percentage';
		$discount_value = (float) ( $applicable_tier['value'] ?? 0 );

		if ( $discount_type === 'percentage' ) {
			return ( $base_price * $quantity ) * ( $discount_value / 100 );
		} else {
			return min( $discount_value * $quantity, $base_price * $quantity );
		}
	}

	/**
	 * Calculate bulk discount.
	 *
	 * @since    1.0.0
	 * @param    SCD_Campaign $campaign       Campaign object.
	 * @param    float        $base_price     Base price.
	 * @param    int          $quantity       Quantity.
	 * @return   float                           Discount amount.
	 */
	private function calculate_bulk_discount( SCD_Campaign $campaign, float $base_price, int $quantity ): float {
		$rules = $campaign->get_discount_rules();

		$min_quantity = (int) ( $rules['min_quantity'] ?? 1 );
		if ( $quantity < $min_quantity ) {
			return 0.0;
		}

		// Use standard discount calculation
		return $this->calculate_discount_amount(
			$campaign,
			$base_price,
			$quantity
		);
	}

	/**
	 * Calculate campaign performance score.
	 *
	 * @since    1.0.0
	 * @param    SCD_Campaign $campaign    Campaign object.
	 * @return   float                        Performance score (0-100).
	 */
	public function calculate_performance_score( SCD_Campaign $campaign ): float {
		if ( ! $this->analytics_repository || ! $campaign->get_id() ) {
			return 0.0;
		}

		$stats = $this->analytics_repository->get_campaign_stats( $campaign->get_id() );

		// Weight different metrics
		$conversion_rate        = $this->calculate_conversion_rate( $campaign );
		$revenue_per_impression = $this->calculate_revenue_per_impression( $campaign );
		$engagement_rate        = $this->calculate_engagement_rate( $campaign );

		// Weighted score calculation
		$score = (
			( $conversion_rate * 0.4 ) + // 40% weight on conversions
			( min( $revenue_per_impression, 100 ) * 0.4 ) + // 40% weight on revenue
			( $engagement_rate * 0.2 )            // 20% weight on engagement
		);

		return min( 100, max( 0, $score ) );
	}

	/**
	 * Calculate revenue per impression.
	 *
	 * @since    1.0.0
	 * @param    SCD_Campaign $campaign    Campaign object.
	 * @return   float                        Revenue per impression.
	 */
	public function calculate_revenue_per_impression( SCD_Campaign $campaign ): float {
		if ( ! $this->analytics_repository || ! $campaign->get_id() ) {
			return 0.0;
		}

		$stats = $this->analytics_repository->get_campaign_stats( $campaign->get_id() );

		$revenue     = (float) ( $stats['revenue'] ?? 0 );
		$impressions = (int) ( $stats['impressions'] ?? 0 );

		if ( $impressions === 0 ) {
			return 0.0;
		}

		return $revenue / $impressions;
	}

	/**
	 * Calculate engagement rate.
	 *
	 * @since    1.0.0
	 * @param    SCD_Campaign $campaign    Campaign object.
	 * @return   float                        Engagement rate percentage.
	 */
	public function calculate_engagement_rate( SCD_Campaign $campaign ): float {
		if ( ! $this->analytics_repository || ! $campaign->get_id() ) {
			return 0.0;
		}

		$stats = $this->analytics_repository->get_campaign_stats( $campaign->get_id() );

		$impressions = (int) ( $stats['impressions'] ?? 0 );
		$clicks      = (int) ( $stats['clicks'] ?? 0 );

		if ( $impressions === 0 ) {
			return 0.0;
		}

		return ( $clicks / $impressions ) * 100;
	}

	/**
	 * Calculate estimated savings for customer.
	 *
	 * @since    1.0.0
	 * @param    SCD_Campaign $campaign       Campaign object.
	 * @param    array        $cart_items     Cart items.
	 * @return   float                           Estimated savings.
	 */
	public function calculate_estimated_savings( SCD_Campaign $campaign, array $cart_items ): float {
		$total_savings = 0.0;

		foreach ( $cart_items as $item ) {
			$product_id = (int) ( $item['product_id'] ?? 0 );
			$quantity   = (int) ( $item['quantity'] ?? 1 );
			$price      = (float) ( $item['price'] ?? 0 );

			if ( $this->can_apply_to_product( $campaign, $product_id ) ) {
				$total_savings += $this->calculate_discount_amount( $campaign, $price, $quantity );
			}
		}

		return $total_savings;
	}

	/**
	 * Check if campaign can apply to product.
	 *
	 * @since    1.0.0
	 * @param    SCD_Campaign $campaign       Campaign object.
	 * @param    int          $product_id     Product ID.
	 * @return   bool                            True if can apply.
	 */
	private function can_apply_to_product( SCD_Campaign $campaign, int $product_id ): bool {
		if ( ! $this->product_selector ) {
			return true; // Assume applicable if no selector
		}

		return $this->product_selector->is_product_eligible( $campaign, $product_id );
	}

	/**
	 * Calculate days remaining for campaign.
	 *
	 * @since    1.0.0
	 * @param    SCD_Campaign $campaign    Campaign object.
	 * @return   int                          Days remaining (-1 if no end date).
	 */
	public function calculate_days_remaining( SCD_Campaign $campaign ): int {
		$ends_at = $campaign->get_ends_at();
		if ( ! $ends_at ) {
			return -1; // No end date
		}

		// Use UTC timezone to match campaign dates (which are stored in UTC)
		$now  = new DateTime( 'now', new DateTimeZone( 'UTC' ) );
		$diff = $ends_at->diff( $now );

		if ( $ends_at < $now ) {
			return 0; // Already ended
		}

		return $diff->days;
	}

	/**
	 * Calculate campaign ROI.
	 *
	 * @since    1.0.0
	 * @param    SCD_Campaign $campaign    Campaign object.
	 * @return   float                        ROI percentage.
	 */
	public function calculate_roi( SCD_Campaign $campaign ): float {
		if ( ! $this->analytics_repository || ! $campaign->get_id() ) {
			return 0.0;
		}

		$stats = $this->analytics_repository->get_campaign_stats( $campaign->get_id() );

		$revenue        = (float) ( $stats['revenue'] ?? 0 );
		$discount_given = (float) ( $stats['discount_given'] ?? 0 );

		if ( $discount_given === 0 ) {
			return 0.0;
		}

		// ROI = (Revenue - Cost) / Cost * 100
		$profit = $revenue - $discount_given;
		return ( $profit / $discount_given ) * 100;
	}

	/**
	 * Get campaign metrics summary.
	 *
	 * @since    1.0.0
	 * @param    SCD_Campaign $campaign    Campaign object.
	 * @return   array                        Metrics summary.
	 */
	public function get_metrics_summary( SCD_Campaign $campaign ): array {
		return array(
			'revenue'                => $this->calculate_revenue( $campaign ),
			'conversion_rate'        => $this->calculate_conversion_rate( $campaign ),
			'performance_score'      => $this->calculate_performance_score( $campaign ),
			'roi'                    => $this->calculate_roi( $campaign ),
			'days_remaining'         => $this->calculate_days_remaining( $campaign ),
			'engagement_rate'        => $this->calculate_engagement_rate( $campaign ),
			'revenue_per_impression' => $this->calculate_revenue_per_impression( $campaign ),
		);
	}
}
